import simpletextfield from './SimpleTextField/Component';
import simpletextarea from './SimpleTextArea/Component';
import simpleradios from './SimpleRadios/Component';
import simplecheckboxes from './SimpleCheckboxes/Component';
import simplepostalcode from './SimplePostalCode/Component';
import header from './Header/Component';
import paragraph from './Paragraph/Component';
import categorycheckboxes from "./CategoryCheckboxes/Component";
import categorytextarea from "./CategoryTextArea/Component";
import categorycommentcontainer from "./CategoryComponentContainer/Component";
import simplehtmlelement from './SimpleHTMLElement/Component';
declare const _default: {
    simpletextfield: typeof simpletextfield;
    simpletextarea: typeof simpletextarea;
    simpleradios: typeof simpleradios;
    simplecheckboxes: typeof simplecheckboxes;
    header: typeof header;
    paragraph: typeof paragraph;
    simplepostalcode: typeof simplepostalcode;
    categorycheckboxes: typeof categorycheckboxes;
    categorytextarea: typeof categorytextarea;
    categorycommentcontainer: typeof categorycommentcontainer;
    simplehtmlelement: typeof simplehtmlelement;
};
export default _default;
